version: '3'

services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app/
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_storage: